[package]
name         = "abstract"
description  = "Abstract the neovim"
version      = { workspace = true }
edition      = { workspace = true }
authors      = { workspace = true }
license      = { workspace = true }
rust-version = { workspace = true }


[lib]
crate-type = ["cdylib"]


[dependencies]
# local libraries
wl_utils    = { workspace = true }
wp_ui       = { workspace = true }
wp_abspm    = { workspace = true }
wp_autogood = { workspace = true }
wp_indent   = { workspace = true }
wp_terminal = { workspace = true }

# 3rd parties libraries
anyhow             = { workspace = true }
git2               = { workspace = true }
nvim-oxi           = { workspace = true }
once_cell          = { workspace = true }
thiserror          = { workspace = true }
tokio              = { workspace = true }
tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
strum              = { workspace = true }
# mlua      = { workspace = true }


[build-dependencies]
nvim-oxi = { workspace = true }
