[package]
name         = "abstract"
description  = "Abstract the neovim"
version      = { workspace = true }
edition      = { workspace = true }
authors      = { workspace = true }
license      = { workspace = true }
rust-version = { workspace = true }


[lib]
crate-type = ["cdylib"]


[dependencies]
# local libraries
wsc_indent = { workspace = true }
wsl_utils  = { workspace = true }

# 3rd parties libraries
nvim-oxi  = { workspace = true }
tokio     = { workspace = true }
thiserror = { workspace = true }
anyhow    = { workspace = true }
mlua      = { workspace = true }
once_cell = "1.21.3"


[build-dependencies]
nvim-oxi = { workspace = true }
