[package]
name         = "abstract"
description  = "Abstract the neovim"
version      = { workspace = true }
edition      = { workspace = true }
authors      = { workspace = true }
license      = { workspace = true }
rust-version = { workspace = true }


[lib]
crate-type = ["cdylib"]


[dependencies]
# local libraries
wsc_indent   = { workspace = true }
wsl_utils    = { workspace = true }
wsp_autogood = { workspace = true }

# 3rd parties libraries
anyhow    = { workspace = true }
mlua      = { workspace = true }
nvim-oxi  = { workspace = true }
once_cell = { workspace = true }
thiserror = { workspace = true }
tokio     = { workspace = true }


[build-dependencies]
nvim-oxi = { workspace = true }
