
--[==[
         collections of commits used to publish stable release
--]==]


return {
	awesome_flutter_snipppets = "",
	ts_context_commentstring  = "",
	cmp_lsp_signature_help    = "",
	telescope_file_browser    = "",
	telescope_media_files     = "",
	telescope_fzf_native      = "",
	telescope_ui_select       = "",
	friendly_snippets         = "",
	indent_blankline          = "",
	session_manager           = "",
	dart_vim_plugin           = "",
	bufferline_lua            = "",
	flutter_tools             = "",
	lsp_installer             = "",
	editorconfig              = "",
	goto_preview              = "",
	web_devicons              = "",
	Abstract_cs               = "",
	cmp_luasnip               = "",
	ts_autotag                = "",
	treesitter                = "",
	playground                = "",
	cmp_buffer                = "",
	lspconfig                 = "",
	impatient                 = "",
	colorizer                 = "",
	autopairs                 = "",
	telescope                 = "",
	maximizer                 = "",
	floaterm                  = "",
	tree_lua                  = "",
	gitsigns                  = "",
	filetype                  = "",
	cmp_path                  = "",
	lspkind                   = "",
	cmp_lua                   = "",
	cmp_lsp                   = "",
	renamer                   = "",
	null_ls                   = "",
	plenary                   = "",
	luasnip                   = "",
	Comment                   = "",
	trouble                   = "",
	packer                    = "",
	feline                    = "",
	penvim                    = "",
	popup                     = "",
	alpha                     = "",
	cmp                       = "",
	hop                       = "",
}

